"""ubah photo ke photo_path

Revision ID: 4fac9d3d61bc
Revises: febfe0a830ea
Create Date: 2025-09-14 00:46:08.837629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fac9d3d61bc'
down_revision = 'febfe0a830ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('photo_data')
        batch_op.drop_column('photo_mimetype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_mimetype', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('photo_data', sa.BLOB(), nullable=True))
        batch_op.drop_column('photo_path')

    # ### end Alembic commands ###
