"""Add barcode_path to GroundCheck

Revision ID: 61785a23818b
Revises: 4fac9d3d61bc
Create Date: 2025-10-31 23:45:49.470926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61785a23818b'
down_revision = '4fac9d3d61bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ground_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ground_check', schema=None) as batch_op:
        batch_op.drop_column('barcode_path')

    # ### end Alembic commands ###
