"""Add profile fields and photo to User

Revision ID: febfe0a830ea
Revises: e5a91459e5ad
Create Date: 2025-09-11 19:24:54.398582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febfe0a830ea'
down_revision = 'e5a91459e5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('nip', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('no_hp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tanggal_lahir', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('jenis_kelamin', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('jabatan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lokasi_penempatan', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('photo_mimetype', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('photo_mimetype')
        batch_op.drop_column('photo_data')
        batch_op.drop_column('lokasi_penempatan')
        batch_op.drop_column('jabatan')
        batch_op.drop_column('jenis_kelamin')
        batch_op.drop_column('tanggal_lahir')
        batch_op.drop_column('no_hp')
        batch_op.drop_column('nip')
        batch_op.drop_column('email')
        batch_op.drop_column('nama')

    # ### end Alembic commands ###
